<?php

return [
    'dictionary' => [
        'hello' => ['sw' => 'Jambo', 'en' => 'Hello', 'pronunciation' => 'JAM-bo'],
        'jambo' => ['sw' => 'Jambo', 'en' => 'Hello', 'pronunciation' => 'JAM-bo'],
        'thank you' => ['sw' => 'Asante', 'en' => 'Thank you', 'pronunciation' => 'ah-SAHN-teh'],
        'asante' => ['sw' => 'Asante', 'en' => 'Thank you', 'pronunciation' => 'ah-SAHN-teh'],
        'how are you' => ['sw' => 'Habari yako?', 'en' => 'How are you?', 'pronunciation' => 'hah-BAH-ree YAH-ko'],
        'habari' => ['sw' => 'Habari', 'en' => 'How are you / News', 'pronunciation' => 'hah-BAH-ree'],
        'habari yako' => ['sw' => 'Habari yako?', 'en' => 'How are you?', 'pronunciation' => 'hah-BAH-ree YAH-ko'],
        'welcome' => ['sw' => 'Karibu', 'en' => 'Welcome', 'pronunciation' => 'kah-REE-boo'],
        'karibu' => ['sw' => 'Karibu', 'en' => 'Welcome', 'pronunciation' => 'kah-REE-boo'],
        'goodbye' => ['sw' => 'Kwaheri', 'en' => 'Goodbye', 'pronunciation' => 'kwah-HEH-ree'],
        'kwaheri' => ['sw' => 'Kwaheri', 'en' => 'Goodbye', 'pronunciation' => 'kwah-HEH-ree'],
        'yes' => ['sw' => 'Ndiyo', 'en' => 'Yes', 'pronunciation' => 'n-DEE-yo'],
        'ndiyo' => ['sw' => 'Ndiyo', 'en' => 'Yes', 'pronunciation' => 'n-DEE-yo'],
        'no' => ['sw' => 'Hapana', 'en' => 'No', 'pronunciation' => 'hah-PAH-nah'],
        'hapana' => ['sw' => 'Hapana', 'en' => 'No', 'pronunciation' => 'hah-PAH-nah'],
        'please' => ['sw' => 'Tafadhali', 'en' => 'Please', 'pronunciation' => 'tah-fah-THAH-lee'],
        'tafadhali' => ['sw' => 'Tafadhali', 'en' => 'Please', 'pronunciation' => 'tah-fah-THAH-lee'],
        'sorry' => ['sw' => 'Pole', 'en' => 'Sorry', 'pronunciation' => 'POH-leh'],
        'pole' => ['sw' => 'Pole', 'en' => 'Sorry', 'pronunciation' => 'POH-leh'],
        'good morning' => ['sw' => 'Habari za asubuhi', 'en' => 'Good morning', 'pronunciation' => 'hah-BAH-ree zah ah-soo-BOO-hee'],
        'good night' => ['sw' => 'Usiku mwema', 'en' => 'Good night', 'pronunciation' => 'oo-SEE-koo m-WEH-mah'],
        'water' => ['sw' => 'Maji', 'en' => 'Water', 'pronunciation' => 'MAH-jee'],
        'maji' => ['sw' => 'Maji', 'en' => 'Water', 'pronunciation' => 'MAH-jee'],
        'food' => ['sw' => 'Chakula', 'en' => 'Food', 'pronunciation' => 'chah-KOO-lah'],
        'chakula' => ['sw' => 'Chakula', 'en' => 'Food', 'pronunciation' => 'chah-KOO-lah'],
        'one' => ['sw' => 'Moja', 'en' => 'One', 'pronunciation' => 'MOH-jah'],
        'moja' => ['sw' => 'Moja', 'en' => 'One', 'pronunciation' => 'MOH-jah'],
        'two' => ['sw' => 'Mbili', 'en' => 'Two', 'pronunciation' => 'MBEE-lee'],
        'mbili' => ['sw' => 'Mbili', 'en' => 'Two', 'pronunciation' => 'MBEE-lee'],
        'three' => ['sw' => 'Tatu', 'en' => 'Three', 'pronunciation' => 'TAH-too'],
        'tatu' => ['sw' => 'Tatu', 'en' => 'Three', 'pronunciation' => 'TAH-too'],
        'four' => ['sw' => 'Nne', 'en' => 'Four', 'pronunciation' => 'N-neh'],
        'nne' => ['sw' => 'Nne', 'en' => 'Four', 'pronunciation' => 'N-neh'],
        'five' => ['sw' => 'Tano', 'en' => 'Five', 'pronunciation' => 'TAH-no'],
        'tano' => ['sw' => 'Tano', 'en' => 'Five', 'pronunciation' => 'TAH-no'],
        'help' => ['sw' => 'Msaada', 'en' => 'Help', 'pronunciation' => 'm-sah-AH-dah'],
        'msaada' => ['sw' => 'Msaada', 'en' => 'Help', 'pronunciation' => 'm-sah-AH-dah'],
        'my name is' => ['sw' => 'Jina langu ni', 'en' => 'My name is', 'pronunciation' => 'JEE-nah LAH-ngoo nee'],
        'what is your name' => ['sw' => 'Jina lako ni nani?', 'en' => 'What is your name?', 'pronunciation' => 'JEE-nah LAH-ko nee NAH-nee'],
        'i am fine' => ['sw' => 'Nzuri', 'en' => 'I am fine', 'pronunciation' => 'n-ZOO-ree'],
        'nzuri' => ['sw' => 'Nzuri', 'en' => 'Fine / Good', 'pronunciation' => 'n-ZOO-ree'],
    ],

    'quick_phrases' => [
        ['en' => 'Hello', 'sw' => 'Jambo', 'pronunciation' => 'JAM-bo'],
        ['en' => 'Thank you', 'sw' => 'Asante', 'pronunciation' => 'ah-SAHN-teh'],
        ['en' => 'How are you?', 'sw' => 'Habari yako?', 'pronunciation' => 'hah-BAH-ree YAH-ko'],
        ['en' => 'Welcome', 'sw' => 'Karibu', 'pronunciation' => 'kah-REE-boo'],
        ['en' => 'Goodbye', 'sw' => 'Kwaheri', 'pronunciation' => 'kwah-HEH-ree'],
    ],

    'chatbot_responses' => [
        'greeting' => 'Jambo! Karibu kwenye Swahili Learning. Ninaweza kukusaidia na salamu, nambari, na maneno ya kawaida. (Hello! Welcome to Swahili Learning. I can help with greetings, numbers, and common words.)',
        'help' => 'Unaweza kuuliza kuhusu: salamu (greetings), nambari (numbers), asante (thank you), au maneno yoyote ya Kiswahili. (You can ask about greetings, numbers, thank you, or any Swahili words.)',
        'default' => 'Samahani, sijaelewa vizuri. Jaribu kuuliza kuhusu salamu, nambari, au maneno ya kawaida. (Sorry, I did not understand. Try asking about greetings, numbers, or common words.)',
    ],
];
